site_name: TIEI IIOT Project Documentation
theme:
  logo: images/cmti_logo_full_white_no_border.png
  name: material
  palette:
    primary: teal
    accent: teal
nav:
    - Project Overview: index.md
    - User Interface: user_interfaces.md
    - Technical Stack: Technical Stack.md
    - Codes & Services Location:
      - TNGA Plant: Code & Services Location/TNGA Plant.md
      - GD Plant: Code & Services Location/GD Plant.md
    - Code Explanation:
      - Collector Services: Code Explanation/Collector.md
      - Back End Services: Code Explanation/Back End.md
    - General Knowledge:
      - Opc Ua: General Knowledge/OPC UA.md
      - KPIs in Manufacturing: General Knowledge/KPI in Manufacturing.md
      - Focas: General Knowledge/Focas.md
      - Manufacturing Management: General Knowledge/Manufacturing Management.md
    - Project Knowledge:
      - Machines: Project Knowledge/Machines.md
      - KPIs Calculations: Project Knowledge/KPI Calculations.md
      - KPIs Calculations (CMTI): Project Knowledge/KPI Calculations (CMTI).md
    - Troubleshooting & FAQ: Troubleshoot_Faq.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - search

extra:
  dev_addr: 0.0.0.0:9999

copyright: For the Love of Manufacturing ❤️